### ISSUE TITLE
eventfd_select_interrupter: Too many open files

### ISSUE THREAD

**Issue by cswilliams** [hapyrus/mysql-replication-listener#33]
I realize you guys aren't the original authors of this library, but you seem to be actively hacking on it, so thought I would report that it appears to leak file descriptors upon reconnect.  You can reproduce it with the following code:

Kodama::Client.start(:host => 'host', :username => 'user', :password => 'pass') do |c|
  c.log_level = :debug # [:debug|:info|:warn|:error|:fatal]
  c.connection_retry_limit = 10000 # times
  c.connection_retry_wait =  0.01 # second
end

Then bounce the mysql server while it is running, the first 100 or so messages will be "Boost error: Connection refused", then after that it prints "eventfd_select_interrupter: Too many open files".

**Comment by makinada** [comment]
Thanks for the report with concrete repro steps.  We'll look into it.

**Comment by cswilliams** [comment]
Hi Mak,

After a lot of debugging this weekend, I think I fixed the issue.  I also fixed several memory leaks that I discovered while I was debugging it.

Please see both pull requests:
https://github.com/hapyrus/mysql-replication-listener/pull/34
https://github.com/hapyrus/ruby-binlog/pull/11

Best,
Chris

**Comment by cswilliams** [comment]
awesome, thanks for merging the PRs (and for all your work maintaining these libraries).
